---
apiVersion: v1
kind: Namespace
metadata:
  name: stolostron
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
  namespace: stolostron
spec:
  targetNamespaces:
  - stolostron
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: stolostron
spec:
  channel: community-0.6
  installPlanApproval: Automatic
  name: stolostron
  source: community-operators
  sourceNamespace: openshift-marketplace